
image: golang:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go mod tidy
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go mod tidy
    - mkdir -p build
    - go build -o build ./...
  artifacts:
    paths:
      - mybinaries

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
