image: golang:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go mod tidy
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  image: docker:latest
  tags:
    - priviliged
  services:
    - docker:dind
  script:
    - docker info #Magic docker fixer line, put this before other docker commands
    - echo "$HARBOR_PSWD" | docker login -u "$HARBOR_UNAME" harbor.sch.bme.hu --password-stdin
    - docker pull muzsikusch:build || true # could use colon, but that fs up the formatting 
    - docker pull muzsikusch:latest || true 
    - docker build --target build --cache-from=muzsikusch:build --tag muzsikusch:build .
    - docker build --cache-from=muzsikusch:build --cache-from=muzsikusch:latest --tag temp .
    - docker tag temp muzsikusch:$CI_COMMIT_SHORT_SHA
    - docker tag temp muzsikusch:latest
    - docker push muzsikusch:build
    - docker push muzsikusch:$CI_COMMIT_SHORT_SHA
    - docker push muzsikusch:latest
    - docker image rm temp muzsikusch:$CI_COMMIT_SHORT_SHA muzsikusch:latest muzsikusch:build

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
