image: golang:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go mod tidy
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  image: docker:latest
  tags:
    - privileged
  services:
    - docker:dind
  script:
    - docker info #Magic docker fixer line, put this before other docker commands
    - echo "$HARBOR_PSWD" | docker login -u "$HARBOR_UNAME" harbor.sch.bme.hu --password-stdin
    - docker pull harbor.sch.bme.hu/private-toth4/muzsikusch:build || true # could use colon, but that fs up the formatting
    - docker pull harbor.sch.bme.hu/private-toth4/muzsikusch:latest || true
    - docker build --target build --cache-from=harbor.sch.bme.hu/private-toth4/muzsikusch:build --tag harbor.sch.bme.hu/private-toth4/muzsikusch:build .
    - docker build --cache-from=harbor.sch.bme.hu/private-toth4/muzsikusch:build --cache-from=harbor.sch.bme.hu/private-toth4/muzsikusch:latest --tag temp .
    - docker tag temp harbor.sch.bme.hu/private-toth4/muzsikusch:$CI_COMMIT_SHORT_SHA
    - docker tag temp harbor.sch.bme.hu/private-toth4/muzsikusch:latest
    - docker push harbor.sch.bme.hu/private-toth4/muzsikusch:build
    - docker push harbor.sch.bme.hu/private-toth4/muzsikusch:$CI_COMMIT_SHORT_SHA
    - docker push harbor.sch.bme.hu/private-toth4/muzsikusch:latest
    - docker image rm temp harbor.sch.bme.hu/private-toth4/muzsikusch:$CI_COMMIT_SHORT_SHA harbor.sch.bme.hu/private-toth4/muzsikusch:latest harbor.sch.bme.hu/private-toth4/muzsikusch:build

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
